# Generated by Django 4.0.1 on 2022-02-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_egn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('software Developer', 1), ('QA Engineer', 2), ('DevOps Specialist', 3)], default='', max_length=20),
            preserve_default=False,
        ),
    ]
