# Generated by Django 4.0.1 on 2022-02-04 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_employee_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
