# Generated by Django 4.0.1 on 2022-02-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
    ]
