# Generated by Django 4.0.1 on 2022-02-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
