# Generated by Django 4.0.1 on 2022-02-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_department_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
