# Generated by Django 4.0.1 on 2022-02-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
